// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20210728082827_AddedCategorySeeding")]
    partial class AddedCategorySeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(2021, 7, 28, 11, 28, 26, 589, DateTimeKind.Local).AddTicks(7451),
                            Description = "Like the phone, but cooler",
                            Name = "Smatrphone",
                            UpdatedDate = new DateTime(2021, 7, 28, 11, 28, 26, 589, DateTimeKind.Local).AddTicks(7451)
                        },
                        new
                        {
                            Id = -2,
                            CreatedDate = new DateTime(2021, 7, 28, 11, 28, 26, 589, DateTimeKind.Local).AddTicks(7451),
                            Description = "Like the smartphone, but bigger",
                            Name = "TV",
                            UpdatedDate = new DateTime(2021, 7, 28, 11, 28, 26, 589, DateTimeKind.Local).AddTicks(7451)
                        },
                        new
                        {
                            Id = -3,
                            CreatedDate = new DateTime(2021, 7, 28, 11, 28, 26, 589, DateTimeKind.Local).AddTicks(7451),
                            Description = "Totally not like a TV, gives you a nice ride though",
                            Name = "Car",
                            UpdatedDate = new DateTime(2021, 7, 28, 11, 28, 26, 589, DateTimeKind.Local).AddTicks(7451)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
