// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20210728092601_AddedProductsSeeding")]
    partial class AddedProductsSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823),
                            Description = "Like the phone, but cooler",
                            Name = "Smatrphone",
                            UpdatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823)
                        },
                        new
                        {
                            Id = -2,
                            CreatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823),
                            Description = "Like the smartphone, but bigger",
                            Name = "TV",
                            UpdatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823)
                        },
                        new
                        {
                            Id = -3,
                            CreatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823),
                            Description = "Totally not like a TV, gives you a nice ride though",
                            Name = "Car",
                            UpdatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823)
                        });
                });

            modelBuilder.Entity("DAL.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823),
                            Description = "Best smartphone for the best daddies",
                            Name = "Shwamsung Galaxy Milky Way 8 - Infinitely Blue",
                            Price = 1337.69m,
                            UpdatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823)
                        },
                        new
                        {
                            Id = -2,
                            CreatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823),
                            Description = "4k to masses, money in cases",
                            Name = "Salami Mi LED TV 4S",
                            Price = 484.74m,
                            UpdatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823)
                        },
                        new
                        {
                            Id = -3,
                            CreatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823),
                            Description = "DC Powah!",
                            Name = "Edison Model S",
                            Price = 123000m,
                            UpdatedDate = new DateTime(2021, 7, 28, 9, 26, 0, 734, DateTimeKind.Utc).AddTicks(9823)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
